# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_child_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ('-created_at',), 'verbose_name': 'Control', 'verbose_name_plural': 'Controles'},
        ),
        migrations.AlterField(
            model_name='control',
            name='age',
            field=models.CharField(blank=True, help_text='Edad en meses', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='weight',
            field=models.CharField(help_text='Altura en  centimetros', max_length=4),
        ),
    ]
