# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20160127_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='control',
            name='weight',
            field=models.CharField(max_length=4),
        ),
    ]
