# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20160203_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='relationship',
            field=models.CharField(default='padre', max_length=20),
            preserve_default=False,
        ),
    ]
