# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 23:43
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20160217_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='celphone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
