# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_auto_20160218_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='head_circumference',
            field=models.DecimalField(decimal_places=2, default=3.4, max_digits=5),
            preserve_default=False,
        ),
    ]
