# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_auto_20160224_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildStimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimulations', to='control.Child')),
            ],
            options={
                'ordering': ('stimulation',),
            },
        ),
        migrations.CreateModel(
            name='Stimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', '1 mes'), ('2', '2 meses'), ('3', '3 meses'), ('4', '4 meses'), ('5', '5 meses'), ('6', '6 meses'), ('7', '7 meses'), ('8', '8 meses'), ('9', '9 meses'), ('10', '10 meses'), ('11', '11 meses'), ('12', '12 meses'), ('14', '14 meses'), ('16', '16 meses'), ('18', '18 meses'), ('20', '20 meses'), ('22', '22 meses'), ('24', '24 meses'), ('30', '30 meses'), ('36', '36 meses'), ('48', '48 meses')], max_length=2)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('month',),
            },
        ),
        migrations.AddField(
            model_name='userchild',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='childstimulation',
            name='stimulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimulations', to='control.Stimulation'),
        ),
        migrations.AlterUniqueTogether(
            name='childstimulation',
            unique_together=set([('child', 'stimulation')]),
        ),
    ]
