# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_auto_20160226_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stimulation',
            options={'ordering': ('month',), 'verbose_name': 'Estimulación', 'verbose_name_plural': 'Estimulaciones'},
        ),
    ]
