# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_request_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
