# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0024_auto_20160408_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay',
            field=models.NullBooleanField(default=False),
        ),
    ]
