# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0025_user_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pay',
        ),
    ]
