# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 21:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinica'), ('POSTA', 'Posta'), ('OTHER', 'Otro')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='longitude/latitude')),
                ('monday_to_friday', models.CharField(max_length=25)),
                ('saturday_sunday_holiday', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Centro  Medico',
                'verbose_name_plural': 'Centros Medicos',
            },
        ),
    ]
