# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedVaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
                ('child_age', models.DateField()),
                ('required', models.BooleanField(default=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('next_applied_date', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='control.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dose', models.CharField(choices=[('1', 'First dose'), ('2', 'Second dose'), ('3', 'Third dose')], max_length=1)),
                ('after_months', models.PositiveSmallIntegerField(blank=True, default=2, null=True)),
                ('details', models.TextField()),
                ('effects', models.TextField()),
                ('related_centers', models.ManyToManyField(related_name='related_vaccines', to='centers.Center')),
                ('related_diseases', models.ManyToManyField(related_name='related_vaccines', to='vaccinations.Disease')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
            },
        ),
        migrations.AddField(
            model_name='appliedvaccine',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_vaccines', to='vaccinations.Vaccine'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccine',
            unique_together=set([('name', 'dose')]),
        ),
        migrations.AlterUniqueTogether(
            name='appliedvaccine',
            unique_together=set([('child', 'vaccine')]),
        ),
    ]
