# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0002_remove_appliedvaccine_child_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedvaccine',
            options={'ordering': ('vaccine',)},
        ),
        migrations.AddField(
            model_name='vaccine',
            name='recommendation',
            field=models.TextField(default='Recomendaciones...'),
            preserve_default=False,
        ),
    ]
