# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 20:49
from __future__ import unicode_literals
from django.db import migrations


def migrate_vaccines(apps, schema_editor):
    Vaccine = apps.get_model("vaccinations", "Vaccine")
    for vaccine in Vaccine.objects.all():
        vaccine.order = vaccine.id
        vaccine.save()


class Migration(migrations.Migration):
    dependencies = [
        ('vaccinations', '0003_auto_20160125_1731'),
    ]

    operations = [
        migrations.RunPython(migrate_vaccines),
    ]
