# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0004_auto_20160203_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
