# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0006_auto_20160204_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedvaccine',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
