# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0008_auto_20160226_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='after_months',
            field=models.PositiveSmallIntegerField(verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='details',
            field=models.TextField(verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='dose',
            field=models.CharField(choices=[('1', 'First dose'), ('2', 'Second dose'), ('3', 'Third dose')], max_length=1, verbose_name='Dosis'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='effects',
            field=models.TextField(verbose_name='Efectos'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='recommendation',
            field=models.TextField(verbose_name='Recomendaciones'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='related_centers',
            field=models.ManyToManyField(related_name='related_vaccines', to='centers.Center', verbose_name='Centros de Vacunación'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='related_diseases',
            field=models.ManyToManyField(related_name='related_vaccines', to='vaccinations.Disease', verbose_name='Emfermedades Relacionadas'),
        ),
    ]
